### ISSUE TITLE
[FEAT]: Signing in as an existing user

### ISSUE THREAD

**Issue by crocsandcoffee** [AndroidDev-social/DodoForMastodon#31]
### Description

Implement functionality to allow existing users to log in

**Comment by crocsandcoffee** [comment]
If anyone is interested on working on this with me, please comment below and ping me in slack.

**Comment by hmncube** [comment]
@crocsandcoffee I would like to work with you on this.

**Comment by crocsandcoffee** [comment]
https://github.com/AndroidDev-social/DodoForMastodon/pull/93

**Comment by crocsandcoffee** [comment]
Completed as part of the following PR https://github.com/AndroidDev-social/DodoForMastodon/pull/93
